name: Flutter Web 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.27.2'
      - name: Enable Flutter Web
        run: flutter config --enable-web
      
      - name: Install Dependencies
        run: flutter packages get
      - name: Build Web
        run: flutter build web --release
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.token }}
          publish_dir: ./build/web
          